function pokemonIdSet() {
  const shuffled = [...gen1Evo].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 8);
}

const gen1Evo = [
  3, // Venusaur (Bulbasaur line)
  6, // Charizard (Charmander line)
  9, // Blastoise (Squirtle line)
  12, // Butterfree (Caterpie line)
  15, // Beedrill (Weedle line)
  18, // Pidgeot (Pidgey line)
  20, // Raticate (Rattata line)
  22, // Fearow (Spearow line)
  24, // Arbok (Ekans line)
  25, // Pikachu
  28, // Sandslash (Sandshrew line)
  31, // Nidoqueen (Nidoran♀ line)
  34, // Nidoking (Nidoran♂ line)
  36, // Clefable (Clefairy line)
  38, // Ninetales (Vulpix line)
  40, // Wigglytuff (Jigglypuff line)
  42, // Golbat (Zubat line)
  45, // Vileplume (Oddish line)
  47, // Parasect (Paras line)
  49, // Venomoth (Venonat line)
  51, // Dugtrio (Diglett line)
  53, // Persian (Meowth line)
  55, // Golduck (Psyduck line)
  57, // Primeape (Mankey line)
  59, // Arcanine (Growlithe line)
  62, // Poliwrath (Poliwag line)
  65, // Alakazam (Abra line)
  68, // Machamp (Machop line)
  71, // Victreebel (Bellsprout line)
  73, // Tentacruel (Tentacool line)
  76, // Golem (Geodude line)
  78, // Rapidash (Ponyta line)
  80, // Slowbro (Slowpoke line)
  82, // Magneton (Magnemite line)
  85, // Dodrio (Doduo line)
  87, // Dewgong (Seel line)
  89, // Muk (Grimer line)
  91, // Cloyster (Shellder line)
  94, // Gengar (Gastly line)
  97, // Hypno (Drowzee line)
  99, // Kingler (Krabby line)
  101, // Electrode (Voltorb line)
  103, // Exeggutor (Exeggcute line)
  105, // Marowak (Cubone line)
  110, // Weezing (Koffing line)
  112, // Rhydon (Rhyhorn line)
  114, // Tangela (no evolution in Gen 1)
  115, // Kangaskhan (no evolution)
  117, // Seadra (Horsea line)
  119, // Seaking (Goldeen line)
  121, // Starmie (Staryu line)
  124, // Jynx (no pre-evolution in Gen 1)
  125, // Electabuzz (no pre-evolution in Gen 1)
  126, // Magmar (no pre-evolution in Gen 1)
  127, // Pinsir (no evolution)
  128, // Tauros (no evolution)
  130, // Gyarados (Magikarp line)
  131, // Lapras (no evolution)
  132, // Ditto (no evolution)
  134, // Vaporeon (Eevee line)
  135, // Jolteon (Eevee line)
  136, // Flareon (Eevee line)
  137, // Porygon (no evolution in Gen 1)
  139, // Omastar (Omanyte line)
  141, // Kabutops (Kabuto line)
  142, // Aerodactyl (no evolution)
  143, // Snorlax (no pre-evolution in Gen 1)
  144, // Articuno (legendary)
  145, // Zapdos (legendary)
  146, // Moltres (legendary)
  149, // Dragonite (Dratini line)
  150, // Mewtwo (legendary)
  151, // Mew (mythical)
];

export { pokemonIdSet };
